### ISSUE TITLE
Please provide doi to enable citation of MindaGap

### ISSUE THREAD

**Issue by pvtodorov** [ViriatoII/MindaGap#11]
Hi,

I would like to cite MindaGap as part of the Resolve segmentation pipeline. If possible, please mint a DOI for the repo (see: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) to make this possible.

Thanks!
Petar

**Comment by ViriatoII** [comment]
Hey Petar,

Made a release, thank you for the suggestion. Here is the DOI:          [10.5281/zenodo.8120558](https://doi.org/10.5281/zenodo.8120558)

And the suggestion of reference:
Ricardo Guerreiro, Florian Wuennemann, & pvtodorov. (2023). ViriatoII/MindaGap: v0.0.3 (0.0.3). Zenodo. https://doi.org/10.5281/zenodo.8120559
 
 Kind regards,
 Ricardo
