### ISSUE TITLE
Dockerfile and CI/CD integration

### ISSUE THREAD

**Issue by ViriatoII** [ViriatoII/MindaGap#2]
Hey @FloWuenne,

Answering your pull request (https://github.com/ViriatoII/MindaGap/pull/1), my first CI attempt fails to install your micromamba yaml environment. It seems opencv 4.6.0 is the origin of the problem.

```
> [3/5] RUN micromamba install -y -n base -f /tmp/env.yaml &&    micromamba clean --all --yes:
#0 0.103         / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
#0 0.103        / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
#0 0.103       /_/
#0 0.103 
#9 26.72 error    libmamba Could not solve for environment specs
#9 26.72 Encountered problems while solving:
#9 26.72   - package libopencv-4.6.0-h06a4308_2 requires opencv 4.6.0, but none of the providers can be installed
#9 26.72 
#9 26.72 The environment can't be solved, aborting the operation
#9 26.74 critical libmamba UnsatisfiableError
------
Dockerfile:3
--------------------
   2 |     COPY --chown=$MAMBA_USER:$MAMBA_USER env.yml /tmp/env.yaml
   3 | >>> RUN micromamba install -y -n base -f /tmp/env.yaml && \
   4 | >>>     micromamba clean --all --yes
   5 |     ARG MAMBA_DOCKERFILE_ACTIVATE=1 
--------------------
ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f /tmp/env.yaml &&     micromamba clean --all --yes" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/usr/local/bin/_dockerfile_shell.sh micromamba install -y -n base -f /tmp/env.yaml &&     micromamba clean --all --yes" did not complete successfully: exit code: 1
```

Trying to do build the image manually has the same error. 

Replacing the opencv version by an older one (4.5.5.62) on your yaml file avoids this error, but ends up in another one:

``` 
#7 39.29 Encountered problems while solving:
#7 39.29   - nothing provides requested libopencv 4.5.5.62**
#7 39.29   - nothing provides requested py-opencv 4.5.5.62**
#7 39.29
#7 39.29 The environment can't be solved, aborting the operation
#7 39.29 error    libmamba Could not solve for environment specs
#7 39.30 critical libmamba UnsatisfiableError

```

I've never used mamba before, am I doing anything wrong?

Cheers,
Ricardo

**Comment by FloWuenne** [comment]
Hi @ViriatoII ,

Thanks for trying to implement the CI. It is a weird error, because the docker build works fine locally on my Mac M1. I guess something must be cached or different in my local conda/mamba environment compared to the micromamba used by the CI build.

I tried a bunch of things today to fix this, but nothing worked... Really weird issue. I will try again in the next few days and try to fix this!

**Comment by FloWuenne** [comment]
Hi @ViriatoII ,

I finally managed to get the CI to work in PR #4 . It was a major pain with openCV dependencies. What did the trick in the end, was to simply remove the OpenCV packages and libopencv from the dependencies list. 

This CI worked on my branch, I hope it will work here as well!

**Comment by ViriatoII** [comment]
Thank you @FloWuenne . That's it then, whenever there is a push, the docker image at dockerhub is updated. You can find it here:

https://hub.docker.com/r/rguerr/mindagap/tags
