### ISSUE TITLE
Error for images with "non-acquired" tiles in find_duplicates.py.

### ISSUE THREAD

**Issue by MicheleBortol** [ViriatoII/MindaGap#3]
Dear all,

Thank you for sharing the scripts.

I tried running `duplicate_finder.py` on two of our samples with the default values for all parameters. The first one completed without any errors, but the second one failed with the following:

```
Traceback (most recent call last):
    File "MindaGap/duplicate_finder.py", line 243, in <module>
        shift = mode3D(pair_xdists, pair_ydists, pair_zdists, minMode)
    File "MindaGap/duplicate_finder.py", line 41, in mode3D
        best = [np.array(x.split(','), dtype=int) for x in count.index[:check_rows]]
    File "MindaGap/duplicate_finder.py", line 41, in <listcomp>
        best = [np.array(x.split(','), dtype=int) for x in count.index[:check_rows]]
ValueError: invalid literal for int() with base 10: ''
```

I suspect that this is because the sample contains tiles with no transcripts (nothing between `xmin` and `xmax` and `ymin` and `ymax`). This causes `df1` to be an empty dataframe, which then causes `find_pot_partners_vertical ` to produce `pair_xdists`, `pair_ydists`, `pair_zdists` all equal to `0`. This makes `coords_3D` = `[0, 0, 0]` and `str_transform` = `['', '', '']`, which results in `counts` being a series containing only the value `3`. This then makes `best = [np.array(x.split(','), dtype=int) for x in count.index[:check_rows]]` fail.

A possible solution could be to skip these empty tiles by adding the following lines after the creation of `df1`:
```
df1 = df[(df.x > xmin)*(df.x < xmax) *
          (df.y > ymin)*(df.y < ymax)].sort_values('y').reset_index()
if df1.empty:
          print(f'Found no transcripts within Y{xmin}:{xmax}, X{ymin}:{ymax}')
          continue     
```
This would be at lines `231` and `274`. 

I could provide a file for testing and I would be happy to submit a pull request if you like. Let me know what you think.

Best,

Michele

**Comment by ViriatoII** [comment]
Dear Michele,

Thanks for the catch! I thought an empty df1 was being dealt with, but I didn't realize `[' ',' ', ' '] `was being counted.

I pushed the changes you suggested. Does it now work without errors? And does it find duplicates in your data?

Cheers,
Ricardo

**Comment by MicheleBortol** [comment]
Dear Ricardo,

Thank you for sorting this out so quickly. I reran the same samples and got no errors.

I still need to fully explore and the results, but they seem fine. For now I am just doing some quick visualization, and the duplicated transcripts look right. Below there is a small cropped example with "duplicates" in green and "non-duplicates" in orange for the ZHFX3 gene. They are not visible in this example, but duplicates are found also along vertical lines.
![duplicate_ZHFX3_cropped](https://user-images.githubusercontent.com/38500587/201346004-6ca37ac2-38dd-4743-b96d-07cd461257de.png).

Best wishes,

Michele

**Comment by ViriatoII** [comment]
Super, thanks! :) 

My biggest fear is that the grid might be slightly irregular, which would make the algorithm miss tile junctions due to jumping on regular 2144 pixel intervals, but so far I have not seen that happening.

Wish you a nice weekend,
Ricardo

**Comment by ViriatoII** [comment]
Hey @MicheleBortol  and @FloWuenne,

Small update for the duplicate_finder script:

As the tilesize might differ between datasets both on X or Y level, I now take two optional arguments: Xtilesize and Ytilesize.

Additionally, a new parameter of [-p True] will create a plot showing the duplications and the searched space, with an annotation of the most common XYZ shift  like this:

![image](https://user-images.githubusercontent.com/25958099/202713782-dd2c9faf-2345-4283-9f4f-69e86c63dde7.png)
