### ISSUE TITLE
Stick version number to Docker container

### ISSUE THREAD

**Issue by FloWuenne** [ViriatoII/MindaGap#7]
Hi Ricardo,

I am currently finishing a nf-core module for MindaGap, to be able to utilize it in my nextflow pipelines and make it easy for other people to do so as well.

https://github.com/nf-core/modules/issues/2477

Currently, the Docker container does not get tagged with the version number you specify in the mindagap.py script. 
Would it be possible to add the version number from Mindagap to the container? The important part for nf-core standards, is that the version number that gets emitted by mindagap.py -v is the same as the docker container version number.

Let me know if I can help with this! 

Cheers

**Comment by ViriatoII** [comment]
Hey Florian,

Sorry for the delay. I'm struggling to implement this, and as I have many things going on at the moment, some help would be very appreciated!

**Comment by FloWuenne** [comment]
Sounds good! I will check in the coming days how to implement this and open some PRs! 

Would you be ok with me creating a recipe for released version being pushed to bioconda? This would make integration into nf-core much easier and fluent. I will let you know whenever a release would need to be created if this is necessary via github.

Since there are multiple scripts in here, I will probably also make the nf-core modules called mindagap/mindagap or mindagap/duplicate_finder etc., so that it's easy to add any scripts for additional functionalities in the future. Does that sound reasonable?

**Comment by ViriatoII** [comment]
Sounds good, yes. Thank you very much for the help! 
I might have a small update of mindagap soon, I've been using it more, as I am developing a rough GUI to let less experienced users fill gaps.

**Comment by FloWuenne** [comment]
Since we will have a biocontainer now, this issue can also be closed. We can also consider if we still want to publish the container on dockerhub via Github action here or if we only provide a working container via biocontainers!
