### ISSUE TITLE
Create release and submit to Bioconda

### ISSUE THREAD

**Issue by FloWuenne** [ViriatoII/MindaGap#8]
Hi RIcardo,

related to my other issue (#7) of versioning the docker container. I have an open PR for turning mindagap into an nf-core module (https://github.com/nf-core/modules/pull/2860) to easily make it useable in nextflow pipelines. For nf-core modules, it is really helpful to have the tool be on bioconda. This has the added benefit, that it automatically creates a versioned container on biocontainers. 

Do you think it would be possible to create versioned releases and upload them to bioconda? This would help tremendously with the continued maintenance of the nf-core module.

**Comment by FloWuenne** [comment]
@ViriatoII Could you make a tagged release for the current version of mindagap (or give me the permission to do so as a collaborator on this repo. I am happy to do it!). Bioconda recipes are better to build using tagged releases and tarballs from Github, as they want stable URLs. Thanks 👍🏻

**Comment by ViriatoII** [comment]
Added you, appreciate the collaboration!

**Comment by FloWuenne** [comment]
Recipe is currently in review. Gotta fix a few kinks but will hopefully be ready soon! 

https://github.com/bioconda/bioconda-recipes/pull/39814

**Comment by FloWuenne** [comment]
Mindagap is now a bioconda package: [https://anaconda.org/bioconda/mindagap](https://anaconda.org/bioconda/mindagap)

The container on quay.io is still blocked but should be enabled soon hopefully. There still seem to be some issues with installation and dependencies when trying to install it via conda somehow. I will fix these in the next days hopefully!

I will close this issue since the conda package is published.
